### ISSUE TITLE
Issues with viewing my pages

### ISSUE THREAD

**Issue by LiamGMaguire** [dh-nuigalway/Early-Modern-Plays#1]
I have uploaded my encoded pages (79-84) onto a separate branch and as separate files, in the branch titled Pages 79-84. The only problem is no one else on the team seems to be able to see these files - definitely messed up something on my end, and not sure how to fix it!

**Comment by jtonra** [comment]
Tagging @davekelly to make sure a notification goes your way!

**Comment by davekelly** [comment]
Hi @LiamGMaguire 

To see your changes the others will need to either check-out your branch, or you'll need to merge your branch into the main branch; others will see your merged changes when they pull from the main branch (i.e. update their local repository from the remote Github repository). You can merge your branch into **main** by using the Pull Request feature on Github (go to https://github.com/dh-nuigalway/Early-Modern-Plays/branches and click "New Pull Request" to start the process).

Here is some info on managing workflows with branches: 

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches
- https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches

And some info about using Pull Requests:

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

It's usually a good idea to merge your branches back into the main branch, and to delete your "work-in-progress" branches (once they've been merged!) as you go along. This avoids you having loads of unnecessary branches in the repository.

cc / @jtonra

**Comment by jtonra** [comment]
Thanks a million, @davekelly! Great to have your advice on this.
Please try to make this a priority, @LiamGMaguire, and update this issue if you have any further problems.
